#!/usr/bin/lua

local hardware_detection = require("lime.hardware_detection")

local eth1_wan = {}

eth1_wan.sectionName = hardware_detection.sectionNamePrefix.."eth1_wan"

function eth1_wan.clean()
	if config.autogenerable(eth1_wan.sectionName) then config.delete(eth1_wan.sectionName) end
end

function eth1_wan.detect_hardware()
	if config.autogenerable(eth1_wan.sectionName) then
		local protos = {}
		for _, proto in pairs(config.get("network", "protocols")) do
			if ( ( proto ~= "lan" ) and ( proto ~= "wan" ) ) then
				table.insert(protos, proto)
			end
		end
		table.insert(protos, "wan")

		config.init_batch()
		config.set(eth1_wan.sectionName, "net")
		config.set(eth1_wan.sectionName, "autogenerated", "true")
		config.set(eth1_wan.sectionName, "protocols", protos)
		config.set(eth1_wan.sectionName, "linux_name", "eth1")
		config.end_batch()
	end
end


return eth1_wan
